version: "3.9"

services:
  web:
    build:
      context: ./source
    image: seedcase_sandbox
    container_name: seedcase_sandbox
    command: python manage.py runserver 0.0.0.0:8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    env_file:
      - ./source/.env.docker
    volumes:
      - ./source:/home/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13-alpine
    env_file:
      - source/.env.docker
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
